name: Send a HTTP Request when new RSS item is detected
on:
  rss:
    url:
      - https://sspai.com/feed
      - https://www.zhihu.com/rss
jobs:
  request:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - name: Make a HTTP Request
        uses: actions/checkout@v2
        with:
          url: https://cubox.pro/c/api/save/od630hfhofe7t1
          method: POST
          body: |
            {
              "link":"${{on.rss.outputs.link}}", 
              "title": "${{on.rss.outputs.title}}",
              "content":"<<<${{on.rss.outputs.contentSnippet}}>>>"
            }
        
